# From here to run again

In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import sklearn.linear_model as models
import numpy as np
import pickle
import sys
import os

os.environ['CUDA_VISIBLE_DEVICES'] = ""
!ls results

DenseNet121c160_features_all.pickle
DenseNet121c160_predictions_all.pickle
DenseNet121c190_predictions_all.pickle
DenseNet121_features_all.pickle
inceptionv3_2018-08-28_features_all.pickle
Inceptionv3a25DataB_features_all.pickle
inceptionv3a25_features_all.pickle
InceptionV3.png
mobile_features_all.pickle
sift_features_all.pickle
submission_2018-08-25（0.02）.txt
submission_2018-08-28_mobile（0.0379）.txt
submission_2018-08-29_00:17:34_inceptionv3_2018-08-28（0.0599）.txt
submission_2018-08-29_01:13:59_Dense121（0.0252）.txt
submission_2018-08-30-06:54:25_DenseNet121+DenseNet121c190（0.0327）.txt
submission_2018-08-30-06:55:38_inceptionv3_2018-08-28+DenseNet121c190（0.0629）.txt
submission_2018-09-02_inceptionv3_2018-08-28+min240（0.0850）.txt
submission_2018-09-02_inceptionv3_2018-08-28+min240-2step-avg（0.0655）.txt
submission_2018-09-02_inceptionv3_2018-08-28+min240-2step-min（0.0600）.txt
submission_2018-09-02_PCAinceptionv3_2018-08-28+min240（0.0845）.txt
submission_2018-09-02_PCAinceptionv3_2018-08-

In [2]:
import pickle

# Load image features
file_feature = './results/' + 'Inceptionv3a25DataB_features_all.pickle'
fdata = open(file_feature, 'rb')
features_dict = pickle.load(fdata)  # variables come out in the order you put them in
fdata.close()
features_all = features_dict['features_all']
labels_all = features_dict['labels_all']
images_all = features_dict['images_all']

# Calculate number
train_num = 0 
test_num = 0
#labels_all 
for lab in labels_all:
    if lab[0] != 't':
        train_num += 1
    else:
        test_num += 1
print(train_num, '\t', test_num)

49028 	 11740


In [3]:
import numpy as np

print(features_all.shape)
print(np.shape(labels_all))
print(np.shape(images_all))
print(features_dict)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [4]:
#features_all = features_dict['features_all']
print(np.max(features_all))
print(np.argmax(features_all))

10375.407
43736268


In [5]:
from sklearn.decomposition import PCA

pca = PCA(n_components=100)
features_all_pca = pca.fit_transform(features_all)

In [6]:
print(features_all_pca.shape)

(60768, 100)


In [7]:
import pandas as pd

f = open(r'/home/anhaoran/data/zero-shot-tianchi/dataset_B/DatasetB_20180919/attributes_per_class.txt')
lines_attr = f.readlines()
attributes = dict()
for each in lines_attr:
    tokens = each.split()
    #print(tokens)
    label = tokens[0]
    attr_list = list()
    for idx in range(1, 26):
        attr_list.append(float(tokens[idx]))
    if not (len(attr_list) == 25):
        print(('attributes number error\n'))
        exit()
    attributes[label] = attr_list
print(attributes)

list_train = list()
list_test = list()
for img_lab in attributes.keys():
    if not img_lab in labels_all:
        list_test.append(img_lab)
    else:
        list_train.append(img_lab)
print(len(list_train))
print(list_train)
print(len(list_test))
print(list_test)

{'ZJL1': [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'ZJL10': [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.7, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'ZJL100': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0], 'ZJL101': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 0.1, 0.3, 0.1, 0.3, 0.1, 0.3, 0.3, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0], 'ZJL102': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0], 'ZJL103': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0], 'ZJL104': [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0], 'ZJL105': [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.

164
['ZJL1', 'ZJL10', 'ZJL100', 'ZJL101', 'ZJL102', 'ZJL103', 'ZJL104', 'ZJL105', 'ZJL106', 'ZJL107', 'ZJL108', 'ZJL109', 'ZJL11', 'ZJL110', 'ZJL111', 'ZJL113', 'ZJL114', 'ZJL115', 'ZJL116', 'ZJL117', 'ZJL118', 'ZJL119', 'ZJL12', 'ZJL120', 'ZJL121', 'ZJL122', 'ZJL123', 'ZJL124', 'ZJL125', 'ZJL126', 'ZJL127', 'ZJL128', 'ZJL129', 'ZJL13', 'ZJL130', 'ZJL131', 'ZJL132', 'ZJL133', 'ZJL135', 'ZJL137', 'ZJL138', 'ZJL139', 'ZJL14', 'ZJL140', 'ZJL141', 'ZJL142', 'ZJL143', 'ZJL144', 'ZJL145', 'ZJL146', 'ZJL147', 'ZJL149', 'ZJL15', 'ZJL150', 'ZJL151', 'ZJL152', 'ZJL153', 'ZJL154', 'ZJL156', 'ZJL157', 'ZJL158', 'ZJL159', 'ZJL16', 'ZJL18', 'ZJL19', 'ZJL2', 'ZJL21', 'ZJL22', 'ZJL23', 'ZJL24', 'ZJL244', 'ZJL247', 'ZJL248', 'ZJL25', 'ZJL254', 'ZJL256', 'ZJL26', 'ZJL261', 'ZJL263', 'ZJL264', 'ZJL265', 'ZJL267', 'ZJL268', 'ZJL273', 'ZJL274', 'ZJL275', 'ZJL276', 'ZJL28', 'ZJL29', 'ZJL3', 'ZJL30', 'ZJL31', 'ZJL32', 'ZJL34', 'ZJL35', 'ZJL36', 'ZJL37', 'ZJL38', 'ZJL39', 'ZJL4', 'ZJL40', 'ZJL41', 'ZJL42', 'Z

In [8]:
# Calculate prototypes (cluster centers)
print(np.max(abs(features_all)))
features_all = features_all/np.max(abs(features_all))
dim_f = features_all.shape[1]
prototypes_train = np.ndarray((len(list_train), dim_f))

dim_a = 25
attributes_train = np.ndarray((len(list_train), dim_a))
attributes_test = np.ndarray((len(list_test), dim_a))

for i in range(len(list_train)):
    label = list_train[i]
    idx = [pos for pos, lab in enumerate(labels_all) if lab == label]
    prototypes_train[i, :] = np.mean(features_all[idx, :], axis=0)
    attributes_train[i, :] = np.asarray(attributes[label])

for i in range(len(list_test)):
    label = list_test[i]
    attributes_test[i, :] = np.asarray(attributes[label])

10375.407


In [9]:
print(prototypes_train.shape)
print(prototypes_train)
print(attributes_train.shape)
print(attributes_train)
print(attributes_test.shape)
print(attributes_test)

(164, 1024)
[[0.00000000e+00 0.00000000e+00 1.48321726e-06 ... 2.61355835e-05
  0.00000000e+00 4.14439825e-07]
 [0.00000000e+00 0.00000000e+00 6.57444332e-07 ... 3.99380988e-05
  1.52951634e-05 1.11945701e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.21376506e-04
  4.35333504e-06 2.75045272e-06]
 ...
 [8.35567153e-06 0.00000000e+00 1.41592136e-06 ... 4.89225713e-05
  1.03341472e-06 1.06643747e-05]
 [4.00892418e-07 0.00000000e+00 0.00000000e+00 ... 1.13386232e-05
  2.45049367e-08 8.92609478e-06]
 [9.18301964e-07 0.00000000e+00 0.00000000e+00 ... 3.28845385e-06
  2.02039064e-06 1.31868428e-05]]
(164, 25)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 0.]]
(121, 25)
[[0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.5 0.5 0. ]
 [1.  0.  0.  ... 0.  1.  0. ]
 ...
 [0.  0.  0.  ... 0.  0.  0. ]
 [1.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.7 0. ]]


In [10]:
# Structure learning
LASSO = models.Lasso(alpha=0.01)
LASSO.fit(attributes_train.transpose(), attributes_test.transpose())
W = LASSO.coef_

# Image prototype synthesis
prototypes_test = (np.dot(prototypes_train.transpose(), W.transpose())).transpose()

In [11]:
# Prediction - 1 step
label = 'test'
idx = [pos for pos, lab in enumerate(labels_all) if lab == label]
features_test = features_all[idx, :]
images_test = [images_all[i] for i in idx]
prediction = list()

for i in range(len(idx)):
    temp = np.repeat(np.reshape((features_test[i, :]), (1, dim_f)), len(list_test), axis=0)
    distance = np.sum((temp - prototypes_test)**2, axis=1)
    pos_unseen = np.argmin(distance)
    diatance_min_unseen = np.min(distance)
    temp = np.repeat(np.reshape((features_test[i, :]), (1, dim_f)), len(list_train), axis=0)
    distance = np.sum((temp - prototypes_train)**2, axis=1)
    pos_seen = np.argmin(distance)
    diatance_min_seen = np.min(distance)
    if diatance_min_seen < diatance_min_unseen:
        prediction.append(list_train[pos_seen])
    else:
        prediction.append(list_test[pos_unseen])

In [12]:
import datetime

now_time = datetime.datetime.now().strftime('%Y-%m-%d')

txtName = "./results/submission_" + now_time + "_inceptionv30910-1step-min.txt"
f=open(txtName, "w")
for i in range(len(prediction)):
    new_context = images_all[train_num + i] +'\t' + prediction[i] + '\n'
    f.write(new_context)
f.close()

sum_unseen = 0
for pre in prediction:
    print(pre)
    if pre in list_test:
        sum_unseen += 1
print(sum_unseen)
print(sum_unseen * 1.0 / len(prediction))

ZJL75
ZJL267
ZJL208
ZJL256
ZJL217
ZJL70
ZJL275
ZJL215
ZJL247
ZJL92
ZJL83
ZJL265
ZJL70
ZJL79
ZJL215
ZJL79
ZJL83
ZJL261
ZJL82
ZJL274
ZJL256
ZJL118
ZJL254
ZJL70
ZJL254
ZJL267
ZJL244
ZJL82
ZJL248
ZJL70
ZJL256
ZJL7
ZJL82
ZJL94
ZJL261
ZJL83
ZJL267
ZJL94
ZJL267
ZJL215
ZJL53
ZJL82
ZJL267
ZJL275
ZJL256
ZJL274
ZJL267
ZJL265
ZJL70
ZJL83
ZJL94
ZJL94
ZJL39
ZJL82
ZJL267
ZJL83
ZJL94
ZJL215
ZJL247
ZJL82
ZJL215
ZJL217
ZJL82
ZJL39
ZJL70
ZJL254
ZJL256
ZJL261
ZJL265
ZJL261
ZJL83
ZJL82
ZJL46
ZJL77
ZJL256
ZJL83
ZJL275
ZJL83
ZJL274
ZJL215
ZJL265
ZJL86
ZJL77
ZJL82
ZJL92
ZJL70
ZJL278
ZJL79
ZJL92
ZJL79
ZJL259
ZJL265
ZJL273
ZJL77
ZJL256
ZJL254
ZJL247
ZJL92
ZJL92
ZJL265
ZJL248
ZJL70
ZJL208
ZJL248
ZJL215
ZJL215
ZJL261
ZJL94
ZJL244
ZJL92
ZJL7
ZJL86
ZJL83
ZJL274
ZJL254
ZJL70
ZJL238
ZJL208
ZJL23
ZJL267
ZJL83
ZJL83
ZJL83
ZJL261
ZJL274
ZJL217
ZJL70
ZJL244
ZJL267
ZJL82
ZJL75
ZJL83
ZJL75
ZJL70
ZJL70
ZJL264
ZJL265
ZJL70
ZJL45
ZJL7
ZJL215
ZJL215
ZJL76
ZJL11
ZJL10
ZJL215
ZJL254
ZJL265
ZJL83
ZJL275
ZJL70
ZJL215
ZJL83
ZJL75
Z

ZJL261
ZJL70
ZJL70
ZJL274
ZJL83
ZJL215
ZJL75
ZJL248
ZJL70
ZJL75
ZJL248
ZJL70
ZJL265
ZJL275
ZJL264
ZJL248
ZJL77
ZJL75
ZJL265
ZJL70
ZJL83
ZJL83
ZJL82
ZJL83
ZJL77
ZJL83
ZJL248
ZJL77
ZJL244
ZJL83
ZJL256
ZJL83
ZJL215
ZJL212
ZJL248
ZJL83
ZJL248
ZJL212
ZJL70
ZJL273
ZJL248
ZJL215
ZJL83
ZJL254
ZJL83
ZJL83
ZJL11
ZJL261
ZJL75
ZJL275
ZJL70
ZJL92
ZJL248
ZJL7
ZJL83
ZJL254
ZJL247
ZJL70
ZJL70
ZJL275
ZJL83
ZJL83
ZJL215
ZJL215
ZJL247
ZJL83
ZJL19
ZJL46
ZJL118
ZJL86
ZJL247
ZJL265
ZJL265
ZJL256
ZJL7
ZJL256
ZJL254
ZJL261
ZJL273
ZJL275
ZJL256
ZJL274
ZJL70
ZJL79
ZJL247
ZJL215
ZJL94
ZJL70
ZJL75
ZJL247
ZJL75
ZJL93
ZJL265
ZJL278
ZJL83
ZJL215
ZJL46
ZJL70
ZJL256
ZJL264
ZJL46
ZJL94
ZJL70
ZJL79
ZJL83
ZJL248
ZJL94
ZJL116
ZJL70
ZJL247
ZJL63
ZJL86
ZJL86
ZJL67
ZJL275
ZJL7
ZJL267
ZJL212
ZJL83
ZJL244
ZJL261
ZJL83
ZJL244
ZJL70
ZJL83
ZJL83
ZJL267
ZJL92
ZJL256
ZJL248
ZJL211
ZJL70
ZJL265
ZJL70
ZJL265
ZJL94
ZJL79
ZJL267
ZJL217
ZJL83
ZJL244
ZJL264
ZJL75
ZJL75
ZJL248
ZJL212
ZJL86
ZJL254
ZJL248
ZJL70
ZJL248
ZJL248
ZJL83
ZJL83
ZJL

ZJL70
ZJL267
ZJL265
ZJL83
ZJL244
ZJL247
ZJL92
ZJL267
ZJL82
ZJL274
ZJL77
ZJL75
ZJL264
ZJL256
ZJL83
ZJL265
ZJL75
ZJL265
ZJL211
ZJL70
ZJL79
ZJL256
ZJL7
ZJL244
ZJL264
ZJL75
ZJL86
ZJL256
ZJL267
ZJL140
ZJL212
ZJL82
ZJL46
ZJL275
ZJL267
ZJL70
ZJL94
ZJL75
ZJL92
ZJL83
ZJL83
ZJL79
ZJL70
ZJL267
ZJL264
ZJL79
ZJL92
ZJL70
ZJL215
ZJL7
ZJL70
ZJL267
ZJL70
ZJL248
ZJL86
ZJL254
ZJL70
ZJL70
ZJL265
ZJL79
ZJL248
ZJL215
ZJL83
ZJL75
ZJL70
ZJL86
ZJL215
ZJL256
ZJL75
ZJL70
ZJL274
ZJL83
ZJL70
ZJL217
ZJL244
ZJL70
ZJL266
ZJL254
ZJL212
ZJL75
ZJL70
ZJL261
ZJL52
ZJL39
ZJL83
ZJL92
ZJL83
ZJL212
ZJL261
ZJL77
ZJL86
ZJL254
ZJL212
ZJL264
ZJL265
ZJL265
ZJL259
ZJL244
ZJL211
ZJL254
ZJL267
ZJL11
ZJL267
ZJL83
ZJL7
ZJL75
ZJL215
ZJL244
ZJL254
ZJL70
ZJL144
ZJL274
ZJL36
ZJL83
ZJL265
ZJL70
ZJL70
ZJL70
ZJL244
ZJL254
ZJL92
ZJL46
ZJL70
ZJL75
ZJL254
ZJL70
ZJL83
ZJL83
ZJL75
ZJL92
ZJL83
ZJL46
ZJL273
ZJL1
ZJL82
ZJL83
ZJL70
ZJL215
ZJL267
ZJL264
ZJL248
ZJL75
ZJL254
ZJL92
ZJL79
ZJL92
ZJL248
ZJL70
ZJL261
ZJL9
ZJL39
ZJL267
ZJL86
ZJL244
ZJL75
ZJL21

ZJL92
ZJL46
ZJL77
ZJL83
ZJL212
ZJL215
ZJL75
ZJL256
ZJL75
ZJL7
ZJL215
ZJL70
ZJL70
ZJL267
ZJL266
ZJL83
ZJL70
ZJL75
ZJL70
ZJL254
ZJL215
ZJL265
ZJL23
ZJL254
ZJL244
ZJL83
ZJL264
ZJL86
ZJL70
ZJL75
ZJL267
ZJL264
ZJL256
ZJL267
ZJL215
ZJL212
ZJL267
ZJL7
ZJL195
ZJL92
ZJL248
ZJL70
ZJL82
ZJL265
ZJL39
ZJL83
ZJL261
ZJL70
ZJL265
ZJL244
ZJL83
ZJL215
ZJL70
ZJL58
ZJL265
ZJL83
ZJL7
ZJL86
ZJL86
ZJL273
ZJL70
ZJL83
ZJL92
ZJL265
ZJL79
ZJL267
ZJL254
ZJL46
ZJL75
ZJL7
ZJL135
ZJL215
ZJL256
ZJL265
ZJL70
ZJL11
ZJL11
ZJL94
ZJL70
ZJL70
ZJL248
ZJL70
ZJL77
ZJL248
ZJL267
ZJL211
ZJL26
ZJL247
ZJL75
ZJL82
ZJL248
ZJL70
ZJL75
ZJL83
ZJL265
ZJL265
ZJL92
ZJL215
ZJL275
ZJL256
ZJL86
ZJL13
ZJL15
ZJL83
ZJL215
ZJL273
ZJL275
ZJL212
ZJL254
ZJL259
ZJL79
ZJL275
ZJL212
ZJL244
ZJL83
ZJL70
ZJL175
ZJL75
ZJL212
ZJL247
ZJL83
ZJL83
ZJL86
ZJL215
ZJL259
ZJL77
ZJL267
ZJL82
ZJL75
ZJL264
ZJL70
ZJL256
ZJL92
ZJL83
ZJL70
ZJL94
ZJL83
ZJL82
ZJL273
ZJL244
ZJL254
ZJL244
ZJL83
ZJL264
ZJL70
ZJL83
ZJL259
ZJL274
ZJL244
ZJL254
ZJL244
ZJL75
ZJL248
ZJL244
ZJL79

ZJL75
ZJL244
ZJL248
ZJL70
ZJL83
ZJL256
ZJL265
ZJL77
ZJL82
ZJL92
ZJL70
ZJL211
ZJL75
ZJL75
ZJL267
ZJL275
ZJL70
ZJL254
ZJL55
ZJL275
ZJL75
ZJL86
ZJL83
ZJL82
ZJL70
ZJL261
ZJL83
ZJL195
ZJL248
ZJL248
ZJL46
ZJL83
ZJL83
ZJL70
ZJL92
ZJL77
ZJL261
ZJL70
ZJL267
ZJL92
ZJL275
ZJL244
ZJL83
ZJL83
ZJL261
ZJL247
ZJL83
ZJL274
ZJL275
ZJL267
ZJL79
ZJL70
ZJL264
ZJL273
ZJL264
ZJL244
ZJL267
ZJL261
ZJL267
ZJL259
ZJL46
ZJL94
ZJL275
ZJL70
ZJL212
ZJL248
ZJL83
ZJL217
ZJL265
ZJL70
ZJL92
ZJL275
ZJL265
ZJL275
ZJL247
ZJL248
ZJL267
ZJL215
ZJL70
ZJL83
ZJL83
ZJL70
ZJL211
ZJL248
ZJL261
ZJL76
ZJL248
ZJL92
ZJL39
ZJL261
ZJL34
ZJL244
ZJL267
ZJL274
ZJL248
ZJL195
ZJL46
ZJL94
ZJL83
ZJL39
ZJL21
ZJL212
ZJL83
ZJL75
ZJL92
ZJL83
ZJL254
ZJL83
ZJL208
ZJL261
ZJL215
ZJL70
ZJL275
ZJL92
ZJL7
ZJL244
ZJL7
ZJL244
ZJL254
ZJL211
ZJL75
ZJL94
ZJL244
ZJL247
ZJL70
ZJL217
ZJL75
ZJL195
ZJL256
ZJL254
ZJL256
ZJL94
ZJL215
ZJL86
ZJL10
ZJL265
ZJL19
ZJL265
ZJL275
ZJL275
ZJL261
ZJL118
ZJL248
ZJL211
ZJL12
ZJL215
ZJL15
ZJL83
ZJL264
ZJL267
ZJL70
ZJL212
ZJL265
Z

ZJL212
ZJL266
ZJL77
ZJL46
ZJL267
ZJL83
ZJL244
ZJL94
ZJL70
ZJL273
ZJL265
ZJL83
ZJL82
ZJL77
ZJL75
ZJL70
ZJL274
ZJL265
ZJL248
ZJL264
ZJL274
ZJL254
ZJL24
ZJL46
ZJL70
ZJL254
ZJL248
ZJL83
ZJL83
ZJL83
ZJL264
ZJL273
ZJL215
ZJL279
ZJL70
ZJL256
ZJL267
ZJL70
ZJL94
ZJL83
ZJL94
ZJL195
ZJL70
ZJL86
ZJL83
ZJL248
ZJL86
ZJL261
ZJL70
ZJL82
ZJL94
ZJL39
ZJL92
ZJL77
ZJL46
ZJL94
ZJL265
ZJL77
ZJL208
ZJL215
ZJL40
ZJL83
ZJL248
ZJL70
ZJL70
ZJL83
ZJL248
ZJL267
ZJL39
ZJL70
ZJL265
ZJL247
ZJL83
ZJL75
ZJL217
ZJL275
ZJL244
ZJL261
ZJL275
ZJL82
ZJL208
ZJL55
ZJL7
ZJL215
ZJL70
ZJL83
ZJL261
ZJL265
ZJL83
ZJL274
ZJL75
ZJL275
ZJL75
ZJL261
ZJL83
ZJL79
ZJL254
ZJL217
ZJL229
ZJL83
ZJL75
ZJL92
ZJL46
ZJL265
ZJL102
ZJL70
ZJL274
ZJL82
ZJL92
ZJL267
ZJL273
ZJL75
ZJL70
ZJL217
ZJL86
ZJL273
ZJL274
ZJL244
ZJL46
ZJL83
ZJL86
ZJL92
ZJL92
ZJL261
ZJL83
ZJL248
ZJL11
ZJL267
ZJL70
ZJL256
ZJL70
ZJL240
ZJL83
ZJL215
ZJL254
ZJL39
ZJL32
ZJL259
ZJL244
ZJL70
ZJL261
ZJL83
ZJL266
ZJL79
ZJL215
ZJL265
ZJL265
ZJL212
ZJL86
ZJL261
ZJL83
ZJL256
ZJL254
ZJL265
ZJL

In [13]:
# Prediction - 2 steps
label = 'test'
idx = [pos for pos, lab in enumerate(labels_all) if lab == label]
#features_test = features_all_pca[idx, :]
features_test = features_all[idx, :]
images_test = [images_all[i] for i in idx]
prediction = list()

distance_min_unseen = 0
distance_avg_unseen = 0
for i in range(len(idx)):
    temp = np.repeat(np.reshape((features_test[i, :]), (1, dim_f)), len(list_test), axis=0)
    distance = np.sum((temp - prototypes_test)**2, axis=1)
    pos = np.argmin(distance)
    if i == 0 or np.min(distance) < distance_min_unseen:
        distance_min_unseen = np.min(distance)
    distance_avg_unseen += np.min(distance)
    prediction.append(list_test[pos])
distance_avg_unseen /= len(idx)

In [14]:
for i in range(len(idx)):
    temp = np.repeat(np.reshape((features_test[i, :]), (1, dim_f)), len(list_train), axis=0)
    distance = np.sum((temp - prototypes_train)**2, axis=1)
    pos = np.argmin(distance)
    #if np.min(distance) < distance_avg_unseen:
    if np.min(distance) < distance_min_unseen:
        prediction[i] = list_train[pos]

In [15]:
import datetime

now_time = datetime.datetime.now().strftime('%Y-%m-%d')

txtName = "./results/submission_" + now_time + "_inceptionv30910-2step-min.txt"
f=open(txtName, "w")
for i in range(len(prediction)):
    new_context = images_all[train_num + i] +'\t' + prediction[i] + '\n'
    f.write(new_context)
f.close()

sum_unseen = 0
for pre in prediction:
    print(pre)
    if pre in list_test:
        sum_unseen += 1
print(sum_unseen)
print(sum_unseen * 1.0 / len(prediction))

ZJL211
ZJL215
ZJL208
ZJL211
ZJL217
ZJL215
ZJL285
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL211
ZJL211
ZJL278
ZJL215
ZJL217
ZJL215
ZJL211
ZJL215
ZJL208
ZJL215
ZJL211
ZJL211
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL278
ZJL215
ZJL215
ZJL285
ZJL217
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL215
ZJL215
ZJL208
ZJL229
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL217
ZJL217
ZJL278
ZJL215
ZJL215
ZJL285
ZJL215
ZJL229
ZJL211
ZJL215
ZJL229
ZJL208
ZJL215
ZJL211
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL285
ZJL215
ZJL278
ZJL278
ZJL215
ZJL278
ZJL259
ZJL215
ZJL211
ZJL215
ZJL285
ZJL211
ZJL215
ZJL215
ZJL215
ZJL195
ZJL278
ZJL215
ZJL208
ZJL217
ZJL215
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL211
ZJL217
ZJL215
ZJL285
ZJL215
ZJL215
ZJL238
ZJL208
ZJL212
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL278
ZJL217
ZJL215
ZJL217
ZJL215
ZJL215
ZJL215
ZJL215
ZJL278
ZJL215
ZJL215
ZJL215
ZJL215
ZJL278
ZJL208
ZJL215
ZJL215
ZJL215
ZJL229

ZJL215
ZJL278
ZJL211
ZJL211
ZJL211
ZJL269
ZJL211
ZJL211
ZJL215
ZJL266
ZJL278
ZJL211
ZJL195
ZJL235
ZJL211
ZJL217
ZJL229
ZJL211
ZJL215
ZJL235
ZJL215
ZJL211
ZJL278
ZJL215
ZJL211
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL212
ZJL83
ZJL215
ZJL215
ZJL215
ZJL211
ZJL211
ZJL278
ZJL215
ZJL215
ZJL278
ZJL215
ZJL215
ZJL278
ZJL217
ZJL208
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL211
ZJL259
ZJL215
ZJL278
ZJL215
ZJL215
ZJL215
ZJL278
ZJL215
ZJL278
ZJL215
ZJL278
ZJL211
ZJL278
ZJL215
ZJL215
ZJL211
ZJL212
ZJL215
ZJL215
ZJL215
ZJL192
ZJL195
ZJL278
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL195
ZJL215
ZJL195
ZJL215
ZJL211
ZJL229
ZJL240
ZJL249
ZJL215
ZJL285
ZJL211
ZJL215
ZJL278
ZJL212
ZJL195
ZJL278
ZJL215
ZJL238
ZJL211
ZJL215
ZJL208
ZJL215
ZJL229
ZJL215
ZJL259
ZJL215
ZJL215
ZJL285
ZJL280
ZJL218
ZJL212
ZJL211
ZJL211
ZJL278
ZJL212
ZJL285
ZJL215
ZJL215
ZJL192
ZJL211
ZJL229
ZJL215
ZJL215
ZJL211
ZJL215
ZJL211
ZJL215
ZJL249
ZJL212
ZJL211
ZJL215
ZJL212
ZJL215
ZJL195
ZJL215
ZJL211
ZJL215


ZJL215
ZJL195
ZJL211
ZJL215
ZJL215
ZJL215
ZJL215
ZJL217
ZJL215
ZJL285
ZJL215
ZJL285
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL217
ZJL215
ZJL215
ZJL285
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL212
ZJL215
ZJL229
ZJL211
ZJL215
ZJL278
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL235
ZJL211
ZJL278
ZJL215
ZJL215
ZJL212
ZJL192
ZJL215
ZJL212
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL278
ZJL215
ZJL217
ZJL211
ZJL215
ZJL215
ZJL215
ZJL211
ZJL208
ZJL215
ZJL212
ZJL215
ZJL215
ZJL215
ZJL278
ZJL215
ZJL211
ZJL215
ZJL211
ZJL215
ZJL211
ZJL278
ZJL217
ZJL211
ZJL211
ZJL215
ZJL208
ZJL215
ZJL215
ZJL215
ZJL215
ZJL195
ZJL211
ZJL215
ZJL215
ZJL175
ZJL215
ZJL208
ZJL215
ZJL215
ZJL211
ZJL217
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL278
ZJL215
ZJL271
ZJL285
ZJL215
ZJL229
ZJL215
ZJL215
ZJL215
ZJL217
ZJL215
ZJL208
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL83
ZJL278
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL217
ZJL215
ZJL215
ZJL211
ZJL217
ZJL178
ZJL215
ZJL215
ZJL211
ZJL215
ZJL211


ZJL278
ZJL215
ZJL211
ZJL211
ZJL259
ZJL215
ZJL259
ZJL278
ZJL229
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL211
ZJL215
ZJL215
ZJL285
ZJL215
ZJL215
ZJL83
ZJL215
ZJL215
ZJL208
ZJL212
ZJL278
ZJL278
ZJL178
ZJL195
ZJL215
ZJL215
ZJL215
ZJL285
ZJL215
ZJL215
ZJL215
ZJL215
ZJL175
ZJL278
ZJL215
ZJL215
ZJL215
ZJL215
ZJL208
ZJL215
ZJL217
ZJL215
ZJL211
ZJL215
ZJL215
ZJL215
ZJL285
ZJL215
ZJL215
ZJL285
ZJL215
ZJL195
ZJL215
ZJL278
ZJL211
ZJL215
ZJL215
ZJL215
ZJL285
ZJL208
ZJL211
ZJL215
ZJL215
ZJL208
ZJL215
ZJL211
ZJL285
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL195
ZJL215
ZJL215
ZJL215
ZJL212
ZJL195
ZJL212
ZJL211
ZJL215
ZJL215
ZJL259
ZJL211
ZJL215
ZJL215
ZJL229
ZJL211
ZJL215
ZJL195
ZJL211
ZJL215
ZJL211
ZJL215
ZJL285
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL229
ZJL211
ZJL278
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL212
ZJL215
ZJL211
ZJL278
ZJL278
ZJL217
ZJL285
ZJL215
ZJL212
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL285


ZJL278
ZJL278
ZJL175
ZJL278
ZJL217
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL229
ZJL215
ZJL211
ZJL215
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL211
ZJL215
ZJL211
ZJL215
ZJL211
ZJL278
ZJL215
ZJL215
ZJL215
ZJL215
ZJL269
ZJL215
ZJL215
ZJL217
ZJL215
ZJL215
ZJL215
ZJL215
ZJL212
ZJL215
ZJL215
ZJL215
ZJL211
ZJL211
ZJL215
ZJL215
ZJL215
ZJL215
ZJL211
ZJL217
ZJL229
ZJL215
ZJL278
ZJL278
ZJL211
ZJL215
ZJL229
ZJL215
ZJL215
ZJL217
ZJL285
ZJL215
ZJL211
ZJL211
ZJL211
ZJL215
ZJL215
ZJL178
ZJL215
ZJL278
ZJL217
ZJL215
ZJL259
ZJL215
ZJL278
ZJL215
ZJL266
ZJL215
ZJL211
ZJL212
ZJL215
ZJL215
ZJL217
ZJL195
ZJL238
ZJL215
ZJL211
ZJL211
ZJL195
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL217
ZJL211
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL278
ZJL278
ZJL83
ZJL211
ZJL175
ZJL215
ZJL195
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL215
ZJL215
ZJL217
ZJL238
ZJL215
ZJL215
ZJL208
ZJL278
ZJL211
ZJL211
ZJL195
ZJL211
ZJL217
ZJL211
ZJL195
ZJL215
ZJL215
ZJL211
ZJL208
ZJL211
ZJL215
ZJL278
ZJL215
ZJL278
ZJL259
ZJL215
ZJL215
ZJL208
ZJL211


ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL211
ZJL211
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL217
ZJL215
ZJL211
ZJL215
ZJL215
ZJL215
ZJL259
ZJL215
ZJL215
ZJL215
ZJL215
ZJL217
ZJL195
ZJL285
ZJL278
ZJL212
ZJL215
ZJL212
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL195
ZJL215
ZJL215
ZJL259
ZJL211
ZJL211
ZJL266
ZJL211
ZJL215
ZJL215
ZJL211
ZJL215
ZJL211
ZJL215
ZJL208
ZJL212
ZJL215
ZJL215
ZJL215
ZJL208
ZJL215
ZJL215
ZJL285
ZJL278
ZJL215
ZJL278
ZJL211
ZJL215
ZJL278
ZJL215
ZJL215
ZJL278
ZJL215
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL285
ZJL195
ZJL215
ZJL285
ZJL215
ZJL235
ZJL215
ZJL215
ZJL211
ZJL215
ZJL229
ZJL211
ZJL215
ZJL215
ZJL285
ZJL215
ZJL211
ZJL215
ZJL211
ZJL215
ZJL215
ZJL211
ZJL217
ZJL278
ZJL215
ZJL211
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL278
ZJL215
ZJL215
ZJL208
ZJL285
ZJL211
ZJL212
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL208
ZJL195
ZJL211
ZJL211
ZJL211
ZJL215
ZJL215
ZJL215
ZJL212
ZJL215
ZJL211
ZJL215
ZJL212
ZJL215
ZJL211
ZJL215
ZJL215
ZJL211

ZJL215
ZJL215
ZJL285
ZJL217
ZJL211
ZJL215
ZJL215
ZJL211
ZJL215
ZJL195
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL278
ZJL215
ZJL195
ZJL215
ZJL215
ZJL215
ZJL215
ZJL217
ZJL211
ZJL215
ZJL229
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL195
ZJL211
ZJL215
ZJL229
ZJL215
ZJL217
ZJL215
ZJL278
ZJL215
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL215
ZJL215
ZJL266
ZJL215
ZJL229
ZJL208
ZJL215
ZJL217
ZJL215
ZJL285
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL278
ZJL211
ZJL195
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL237
ZJL285
ZJL215
ZJL215
ZJL215
ZJL215
ZJL278
ZJL195
ZJL208
ZJL259
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL249
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL211
ZJL215
ZJL211
ZJL215
ZJL215
ZJL215
ZJL208
ZJL278
ZJL215
ZJL215
ZJL259
ZJL215
ZJL215
ZJL211
ZJL215
ZJL215
ZJL215
ZJL208
ZJL195
ZJL215
ZJL215
ZJL217
ZJL285
ZJL211
ZJL215
ZJL211
ZJL259
ZJL215
ZJL278
ZJL208
ZJL215
ZJL215
ZJL215
ZJL212
ZJL211
ZJL215
ZJL217
ZJL217
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL215
ZJL208
ZJL215
ZJL215

In [16]:
for i in range(len(idx)):
    temp = np.repeat(np.reshape((features_test[i, :]), (1, dim_f)), len(list_train), axis=0)
    distance = np.sum((temp - prototypes_train)**2, axis=1)
    pos = np.argmin(distance)
    if np.min(distance) < distance_avg_unseen:
    #if np.min(distance) < distance_min_unseen:
        prediction[i] = list_train[pos]

In [17]:
print(np.shape(images_all[train_num:]))
print(images_all[train_num])
print(np.shape(prediction))
print(prediction)

(11740,)
0003ae092034aa69da9782b2a3b4a15a.jpg
(11740,)
['ZJL75', 'ZJL267', 'ZJL248', 'ZJL256', 'ZJL265', 'ZJL70', 'ZJL275', 'ZJL247', 'ZJL247', 'ZJL92', 'ZJL83', 'ZJL265', 'ZJL70', 'ZJL79', 'ZJL247', 'ZJL79', 'ZJL83', 'ZJL261', 'ZJL82', 'ZJL274', 'ZJL256', 'ZJL118', 'ZJL254', 'ZJL70', 'ZJL254', 'ZJL267', 'ZJL244', 'ZJL82', 'ZJL248', 'ZJL70', 'ZJL256', 'ZJL7', 'ZJL82', 'ZJL94', 'ZJL261', 'ZJL83', 'ZJL267', 'ZJL94', 'ZJL267', 'ZJL247', 'ZJL53', 'ZJL82', 'ZJL267', 'ZJL275', 'ZJL256', 'ZJL274', 'ZJL267', 'ZJL265', 'ZJL70', 'ZJL83', 'ZJL94', 'ZJL94', 'ZJL39', 'ZJL82', 'ZJL267', 'ZJL83', 'ZJL94', 'ZJL275', 'ZJL247', 'ZJL82', 'ZJL247', 'ZJL75', 'ZJL82', 'ZJL39', 'ZJL70', 'ZJL254', 'ZJL256', 'ZJL261', 'ZJL265', 'ZJL261', 'ZJL83', 'ZJL82', 'ZJL46', 'ZJL77', 'ZJL256', 'ZJL83', 'ZJL275', 'ZJL83', 'ZJL274', 'ZJL247', 'ZJL265', 'ZJL86', 'ZJL77', 'ZJL82', 'ZJL92', 'ZJL70', 'ZJL267', 'ZJL79', 'ZJL92', 'ZJL79', 'ZJL275', 'ZJL265', 'ZJL273', 'ZJL77', 'ZJL256', 'ZJL254', 'ZJL247', 'ZJL92', 'ZJL92', 'ZJL

In [18]:
import datetime

now_time = datetime.datetime.now().strftime('%Y-%m-%d')

txtName = "./results/submission_" + now_time + "_inceptionv30910-2step-avg.txt"
f=open(txtName, "w")
for i in range(len(prediction)):
    new_context = images_all[train_num + i] +'\t' + prediction[i] + '\n'
    f.write(new_context)
f.close()

In [19]:
sum_unseen = 0
for pre in prediction:
    print(pre)
    if pre in list_test:
        sum_unseen += 1
print(sum_unseen)
print(sum_unseen * 1.0 / len(prediction))

ZJL75
ZJL267
ZJL248
ZJL256
ZJL265
ZJL70
ZJL275
ZJL247
ZJL247
ZJL92
ZJL83
ZJL265
ZJL70
ZJL79
ZJL247
ZJL79
ZJL83
ZJL261
ZJL82
ZJL274
ZJL256
ZJL118
ZJL254
ZJL70
ZJL254
ZJL267
ZJL244
ZJL82
ZJL248
ZJL70
ZJL256
ZJL7
ZJL82
ZJL94
ZJL261
ZJL83
ZJL267
ZJL94
ZJL267
ZJL247
ZJL53
ZJL82
ZJL267
ZJL275
ZJL256
ZJL274
ZJL267
ZJL265
ZJL70
ZJL83
ZJL94
ZJL94
ZJL39
ZJL82
ZJL267
ZJL83
ZJL94
ZJL275
ZJL247
ZJL82
ZJL247
ZJL75
ZJL82
ZJL39
ZJL70
ZJL254
ZJL256
ZJL261
ZJL265
ZJL261
ZJL83
ZJL82
ZJL46
ZJL77
ZJL256
ZJL83
ZJL275
ZJL83
ZJL274
ZJL247
ZJL265
ZJL86
ZJL77
ZJL82
ZJL92
ZJL70
ZJL267
ZJL79
ZJL92
ZJL79
ZJL275
ZJL265
ZJL273
ZJL77
ZJL256
ZJL254
ZJL247
ZJL92
ZJL92
ZJL265
ZJL248
ZJL70
ZJL248
ZJL248
ZJL254
ZJL247
ZJL261
ZJL94
ZJL244
ZJL92
ZJL7
ZJL86
ZJL83
ZJL274
ZJL254
ZJL70
ZJL99
ZJL76
ZJL23
ZJL267
ZJL83
ZJL83
ZJL83
ZJL261
ZJL274
ZJL254
ZJL70
ZJL244
ZJL267
ZJL82
ZJL75
ZJL83
ZJL75
ZJL70
ZJL70
ZJL264
ZJL265
ZJL70
ZJL45
ZJL7
ZJL247
ZJL247
ZJL76
ZJL11
ZJL10
ZJL83
ZJL254
ZJL265
ZJL83
ZJL275
ZJL70
ZJL70
ZJL83
ZJL75
ZJL76


ZJL70
ZJL248
ZJL83
ZJL248
ZJL248
ZJL70
ZJL273
ZJL248
ZJL247
ZJL83
ZJL254
ZJL83
ZJL83
ZJL11
ZJL261
ZJL75
ZJL275
ZJL70
ZJL92
ZJL248
ZJL7
ZJL83
ZJL254
ZJL247
ZJL70
ZJL70
ZJL275
ZJL83
ZJL83
ZJL248
ZJL83
ZJL247
ZJL83
ZJL19
ZJL46
ZJL118
ZJL86
ZJL247
ZJL265
ZJL265
ZJL256
ZJL7
ZJL256
ZJL254
ZJL261
ZJL273
ZJL275
ZJL256
ZJL274
ZJL70
ZJL79
ZJL247
ZJL247
ZJL94
ZJL70
ZJL75
ZJL247
ZJL75
ZJL178
ZJL265
ZJL79
ZJL83
ZJL247
ZJL46
ZJL70
ZJL256
ZJL264
ZJL46
ZJL94
ZJL70
ZJL79
ZJL83
ZJL248
ZJL94
ZJL116
ZJL70
ZJL247
ZJL63
ZJL86
ZJL86
ZJL67
ZJL275
ZJL7
ZJL267
ZJL70
ZJL83
ZJL244
ZJL261
ZJL83
ZJL244
ZJL70
ZJL83
ZJL83
ZJL267
ZJL92
ZJL256
ZJL248
ZJL265
ZJL70
ZJL265
ZJL70
ZJL265
ZJL94
ZJL79
ZJL267
ZJL256
ZJL83
ZJL244
ZJL264
ZJL75
ZJL75
ZJL248
ZJL75
ZJL86
ZJL254
ZJL248
ZJL70
ZJL248
ZJL248
ZJL83
ZJL83
ZJL248
ZJL248
ZJL77
ZJL39
ZJL76
ZJL75
ZJL244
ZJL70
ZJL274
ZJL248
ZJL265
ZJL83
ZJL244
ZJL254
ZJL261
ZJL94
ZJL274
ZJL274
ZJL275
ZJL244
ZJL244
ZJL254
ZJL256
ZJL77
ZJL247
ZJL75
ZJL39
ZJL83
ZJL70
ZJL15
ZJL70
ZJL248
ZJL248
ZJ

ZJL256
ZJL70
ZJL86
ZJL275
ZJL75
ZJL267
ZJL247
ZJL244
ZJL275
ZJL248
ZJL265
ZJL75
ZJL254
ZJL70
ZJL1
ZJL45
ZJL70
ZJL70
ZJL83
ZJL70
ZJL83
ZJL38
ZJL247
ZJL83
ZJL70
ZJL244
ZJL265
ZJL275
ZJL261
ZJL248
ZJL77
ZJL244
ZJL83
ZJL86
ZJL7
ZJL94
ZJL77
ZJL178
ZJL254
ZJL70
ZJL256
ZJL264
ZJL248
ZJL254
ZJL83
ZJL79
ZJL244
ZJL118
ZJL264
ZJL38
ZJL275
ZJL247
ZJL7
ZJL40
ZJL267
ZJL247
ZJL86
ZJL83
ZJL83
ZJL83
ZJL10
ZJL265
ZJL274
ZJL94
ZJL92
ZJL264
ZJL248
ZJL70
ZJL254
ZJL70
ZJL265
ZJL267
ZJL254
ZJL70
ZJL275
ZJL83
ZJL83
ZJL261
ZJL267
ZJL261
ZJL247
ZJL244
ZJL264
ZJL70
ZJL83
ZJL79
ZJL265
ZJL77
ZJL83
ZJL92
ZJL244
ZJL7
ZJL77
ZJL256
ZJL261
ZJL94
ZJL247
ZJL75
ZJL70
ZJL92
ZJL77
ZJL70
ZJL267
ZJL83
ZJL75
ZJL83
ZJL63
ZJL248
ZJL247
ZJL244
ZJL248
ZJL275
ZJL77
ZJL75
ZJL77
ZJL92
ZJL75
ZJL248
ZJL244
ZJL75
ZJL40
ZJL264
ZJL83
ZJL86
ZJL275
ZJL82
ZJL265
ZJL86
ZJL265
ZJL23
ZJL261
ZJL118
ZJL273
ZJL46
ZJL94
ZJL118
ZJL273
ZJL75
ZJL92
ZJL70
ZJL75
ZJL247
ZJL275
ZJL244
ZJL41
ZJL79
ZJL70
ZJL70
ZJL75
ZJL261
ZJL7
ZJL247
ZJL248
ZJL256
ZJL82
ZJ

ZJL79
ZJL92
ZJL75
ZJL254
ZJL83
ZJL247
ZJL261
ZJL244
ZJL77
ZJL248
ZJL267
ZJL26
ZJL77
ZJL265
ZJL273
ZJL47
ZJL247
ZJL77
ZJL265
ZJL79
ZJL94
ZJL247
ZJL256
ZJL254
ZJL94
ZJL247
ZJL256
ZJL273
ZJL267
ZJL247
ZJL82
ZJL247
ZJL7
ZJL82
ZJL248
ZJL82
ZJL248
ZJL86
ZJL265
ZJL75
ZJL275
ZJL118
ZJL7
ZJL247
ZJL70
ZJL244
ZJL79
ZJL83
ZJL79
ZJL264
ZJL83
ZJL82
ZJL140
ZJL70
ZJL82
ZJL82
ZJL37
ZJL83
ZJL254
ZJL92
ZJL244
ZJL70
ZJL70
ZJL265
ZJL265
ZJL83
ZJL86
ZJL75
ZJL254
ZJL46
ZJL86
ZJL141
ZJL275
ZJL63
ZJL98
ZJL77
ZJL83
ZJL254
ZJL83
ZJL267
ZJL75
ZJL274
ZJL39
ZJL70
ZJL83
ZJL77
ZJL248
ZJL244
ZJL267
ZJL248
ZJL267
ZJL83
ZJL261
ZJL256
ZJL7
ZJL82
ZJL256
ZJL70
ZJL274
ZJL254
ZJL98
ZJL92
ZJL248
ZJL70
ZJL274
ZJL70
ZJL265
ZJL261
ZJL141
ZJL267
ZJL265
ZJL261
ZJL265
ZJL83
ZJL267
ZJL45
ZJL75
ZJL247
ZJL267
ZJL70
ZJL83
ZJL267
ZJL248
ZJL70
ZJL244
ZJL264
ZJL244
ZJL77
ZJL244
ZJL94
ZJL254
ZJL248
ZJL39
ZJL70
ZJL46
ZJL75
ZJL77
ZJL83
ZJL94
ZJL122
ZJL244
ZJL140
ZJL248
ZJL92
ZJL70
ZJL261
ZJL24
ZJL70
ZJL247
ZJL86
ZJL247
ZJL70
ZJL273
ZJL244
ZJ

ZJL7
ZJL256
ZJL82
ZJL76
ZJL247
ZJL273
ZJL248
ZJL254
ZJL83
ZJL79
ZJL92
ZJL247
ZJL83
ZJL264
ZJL267
ZJL267
ZJL77
ZJL248
ZJL256
ZJL46
ZJL75
ZJL83
ZJL273
ZJL256
ZJL247
ZJL83
ZJL86
ZJL265
ZJL256
ZJL273
ZJL70
ZJL94
ZJL267
ZJL94
ZJL265
ZJL86
ZJL273
ZJL256
ZJL248
ZJL261
ZJL46
ZJL75
ZJL261
ZJL70
ZJL83
ZJL267
ZJL83
ZJL265
ZJL247
ZJL83
ZJL275
ZJL92
ZJL261
ZJL254
ZJL256
ZJL92
ZJL92
ZJL267
ZJL83
ZJL267
ZJL275
ZJL247
ZJL254
ZJL274
ZJL92
ZJL118
ZJL70
ZJL256
ZJL135
ZJL86
ZJL264
ZJL256
ZJL267
ZJL77
ZJL92
ZJL254
ZJL92
ZJL94
ZJL83
ZJL38
ZJL267
ZJL248
ZJL256
ZJL92
ZJL38
ZJL256
ZJL265
ZJL70
ZJL92
ZJL254
ZJL273
ZJL70
ZJL254
ZJL86
ZJL264
ZJL247
ZJL94
ZJL256
ZJL254
ZJL83
ZJL70
ZJL92
ZJL1
ZJL244
ZJL83
ZJL254
ZJL83
ZJL82
ZJL275
ZJL70
ZJL248
ZJL244
ZJL273
ZJL254
ZJL70
ZJL70
ZJL79
ZJL75
ZJL86
ZJL264
ZJL10
ZJL248
ZJL122
ZJL92
ZJL46
ZJL86
ZJL94
ZJL9
ZJL267
ZJL75
ZJL265
ZJL261
ZJL256
ZJL70
ZJL82
ZJL75
ZJL264
ZJL70
ZJL10
ZJL70
ZJL77
ZJL275
ZJL261
ZJL273
ZJL261
ZJL248
ZJL248
ZJL7
ZJL75
ZJL79
ZJL254
ZJL92
ZJL275
ZJL70
Z

ZJL70
ZJL70
ZJL248
ZJL265
ZJL261
ZJL244
ZJL256
ZJL248
ZJL248
ZJL256
ZJL83
ZJL92
ZJL83
ZJL83
ZJL70
ZJL10
ZJL70
ZJL76
ZJL70
ZJL70
ZJL83
ZJL83
ZJL265
ZJL247
ZJL264
ZJL267
ZJL83
ZJL83
ZJL83
ZJL45
ZJL38
ZJL70
ZJL83
ZJL47
ZJL273
ZJL248
ZJL75
ZJL267
ZJL248
ZJL83
ZJL63
ZJL261
ZJL70
ZJL70
ZJL77
ZJL70
ZJL91
ZJL92
ZJL254
ZJL264
ZJL46
ZJL70
ZJL83
ZJL273
ZJL248
ZJL75
ZJL19
ZJL70
ZJL256
ZJL261
ZJL83
ZJL244
ZJL70
ZJL267
ZJL86
ZJL75
ZJL70
ZJL11
ZJL83
ZJL102
ZJL92
ZJL75
ZJL70
ZJL75
ZJL273
ZJL265
ZJL256
ZJL82
ZJL248
ZJL265
ZJL79
ZJL265
ZJL247
ZJL94
ZJL254
ZJL92
ZJL82
ZJL75
ZJL248
ZJL244
ZJL70
ZJL275
ZJL275
ZJL248
ZJL256
ZJL244
ZJL247
ZJL92
ZJL40
ZJL92
ZJL70
ZJL83
ZJL274
ZJL244
ZJL79
ZJL39
ZJL244
ZJL82
ZJL248
ZJL83
ZJL70
ZJL82
ZJL75
ZJL70
ZJL70
ZJL247
ZJL86
ZJL256
ZJL267
ZJL83
ZJL247
ZJL79
ZJL264
ZJL83
ZJL92
ZJL70
ZJL82
ZJL75
ZJL70
ZJL77
ZJL247
ZJL70
ZJL76
ZJL70
ZJL70
ZJL273
ZJL267
ZJL10
ZJL46
ZJL46
ZJL248
ZJL77
ZJL70
ZJL247
ZJL256
ZJL248
ZJL70
ZJL256
ZJL244
ZJL82
ZJL70
ZJL46
ZJL247
ZJL7
ZJL77
ZJL7
ZJL24

# PCA

In [23]:
# Calculate PCA prototypes (cluster centers)
print(np.max(abs(features_all_pca)))
features_all_pca = features_all_pca/np.max(abs(features_all_pca))
dim_f = features_all_pca.shape[1]
prototypes_train = np.ndarray((len(list_train), dim_f))

dim_a = 25
attributes_train = np.ndarray((len(list_train), dim_a))
attributes_test = np.ndarray((len(list_test), dim_a))

for i in range(len(list_train)):
    label = list_train[i]
    idx = [pos for pos, lab in enumerate(labels_all) if lab == label]
    prototypes_train[i, :] = np.mean(features_all_pca[idx, :], axis=0)
    attributes_train[i, :] = np.asarray(attributes[label])

for i in range(len(list_test)):
    label = list_test[i]
    attributes_test[i, :] = np.asarray(attributes[label])

0.00043302524


In [24]:
print(prototypes_train.shape)
print(prototypes_train)
print(attributes_train.shape)
print(attributes_train)
print(attributes_test.shape)
print(attributes_test)

(190, 100)
[[ 9.92993951e-01  2.70266514e-06  2.05545334e-07 ... -4.31812724e-10
   8.56893945e-10  9.50644119e-10]
 [ 9.92997289e-01 -7.29937977e-09 -2.13642926e-09 ...  1.50836667e-12
  -3.32489570e-12 -2.66874738e-12]
 [ 9.92997110e-01 -7.29937932e-09 -2.13642948e-09 ...  1.50836808e-12
  -3.32489570e-12 -2.66874825e-12]
 ...
 [ 9.92997050e-01 -7.29937932e-09 -2.13642970e-09 ...  1.50836863e-12
  -3.32489570e-12 -2.66874869e-12]
 [ 9.92997110e-01 -5.78144750e-08  1.96164702e-08 ...  4.04061637e-12
  -2.98412965e-12 -1.87984558e-11]
 [ 9.92997169e-01 -7.29937932e-09 -2.13642948e-09 ...  1.50836797e-12
  -3.32489591e-12 -2.66874804e-12]]
(190, 25)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 0.]]
(40, 25)
[[0.  1.  0.  0.  0.  0.  0.8 0.8 0.  0.5 0.  0.2 0.3 0.  0.  0.  0.  0.
  0.3 0.5 0.  0.5 0.5 0.5 0. ]
 [1.  0.  0.  0.  0.  0.  0.5 0.5 0.1 0.  0.  0.  0.  0.  0.  0.  0.  0.
 

In [25]:
# Structure learning
LASSO = models.Lasso(alpha=0.01)
LASSO.fit(attributes_train.transpose(), attributes_test.transpose())
W = LASSO.coef_

# Image prototype synthesis
prototypes_test = (np.dot(prototypes_train.transpose(), W.transpose())).transpose()

In [26]:
# Prediction - 1 step
label = 'test'
idx = [pos for pos, lab in enumerate(labels_all) if lab == label]
features_test = features_all_pca[idx, :]
#features_test = features_all[idx, :]
images_test = [images_all[i] for i in idx]
prediction = list()

for i in range(len(idx)):
    temp = np.repeat(np.reshape((features_test[i, :]), (1, dim_f)), len(list_test), axis=0)
    distance = np.sum((temp - prototypes_test)**2, axis=1)
    pos_unseen = np.argmin(distance)
    diatance_min_unseen = np.min(distance)
    temp = np.repeat(np.reshape((features_test[i, :]), (1, dim_f)), len(list_train), axis=0)
    distance = np.sum((temp - prototypes_train)**2, axis=1)
    pos_seen = np.argmin(distance)
    diatance_min_seen = np.min(distance)
    if diatance_min_seen < diatance_min_unseen:
        prediction.append(list_train[pos_seen])
    else:
        prediction.append(list_test[pos_unseen])

In [30]:
# Prediction - 2 steps
label = 'test'
idx = [pos for pos, lab in enumerate(labels_all) if lab == label]
features_test = features_all_pca[idx, :]
#features_test = features_all[idx, :]
images_test = [images_all[i] for i in idx]
prediction = list()

distance_min_unseen = 0
distance_avg_unseen = 0
for i in range(len(idx)):
    temp = np.repeat(np.reshape((features_test[i, :]), (1, dim_f)), len(list_test), axis=0)
    distance = np.sum((temp - prototypes_test)**2, axis=1)
    pos = np.argmin(distance)
    if i == 0 or np.min(distance) < distance_min_unseen:
        distance_min_unseen = np.min(distance)
    #distance_avg_unseen += np.min(distance)
    prediction.append(list_test[pos])
distance_avg_unseen /= len(idx)
    
for i in range(len(idx)):
    temp = np.repeat(np.reshape((features_test[i, :]), (1, dim_f)), len(list_train), axis=0)
    distance = np.sum((temp - prototypes_train)**2, axis=1)
    pos = np.argmin(distance)
    #if np.min(distance) < distance_avg_unseen:
    if np.min(distance) < distance_min_unseen:
        prediction[i] = list_train[pos]

In [31]:
print(np.shape(images_all[train_num:]))
print(images_all[train_num])
print(np.shape(prediction))
print(prediction)

(14633,)
00ddbe75d7aff5037d360401af02ca57.jpg
(14633,)
['ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10', 'ZJL10',

In [54]:
import datetime

now_time = datetime.datetime.now().strftime('%Y-%m-%d')

txtName = "./results/submission_" + now_time + "_PCAinceptionv3a25+min240-2step-avg.txt"
f=open(txtName, "w")
for i in range(len(prediction)):
    new_context = images_all[train_num + i] +'\t' + prediction[i] + '\n'
    f.write(new_context)
f.close()

In [55]:
sum_unseen = 0
for pre in prediction:
    print(int(pre[3:]))
    if int(pre[3:]) > 200:
        sum_unseen += 1
print(sum_unseen)
print(sum_unseen * 1.0 / len(prediction))

44
215
174
239
110
139
193
167
70
177
171
70
24
70
43
1
56
58
24
24
24
51
1
1
147
80
32
188
24
193
82
184
113
48
189
57
167
119
14
118
1
1
43
1
1
35
239
189
215
185
70
70
1
35
118
58
44
1
194
64
149
24
165
100
46
1
145
24
187
200
124
185
1
183
1
78
35
38
171
83
188
32
188
24
118
177
118
14
4
141
177
118
52
40
143
182
192
192
118
172
84
118
177
43
83
126
119
70
44
13
188
195
129
179
46
177
130
84
82
118
22
199
40
79
14
77
146
177
177
172
24
174
168
177
139
167
4
215
124
141
94
14
1
184
191
1
71
145
90
3
156
177
1
146
4
87
24
21
43
215
1
139
1
116
83
7
52
174
177
174
105
84
115
177
32
127
115
139
192
177
40
192
143
1
25
75
82
133
118
177
69
72
24
52
127
1
122
46
63
3
118
166
188
69
40
119
130
99
94
172
43
118
21
1
118
24
177
24
39
162
177
43
64
24
177
1
75
127
43
215
44
5
75
174
118
94
5
118
118
1
239
14
143
118
1
1
104
153
43
118
40
23
37
62
98
4
118
43
127
90
1
159
43
1
192
116
1
68
167
109
189
196
14
11
60
174
153
177
177
10
39
154
1
6
124
153
75
184
24
1
118
174
113
57
44
215
177
29


24
21
1
75
195
90
68
1
1
75
24
24
43
24
194
58
159
183
24
43
43
1
200
193
24
1
171
1
41
177
92
199
75
68
1
118
215
43
75
24
90
109
82
116
43
171
184
1
145
21
85
14
90
177
6
171
156
195
174
43
24
68
102
153
24
23
198
116
190
196
185
55
215
167
153
195
215
63
94
239
153
24
24
118
40
118
199
177
24
116
90
177
138
163
171
1
116
163
94
174
1
96
153
43
199
177
70
70
153
165
129
149
171
130
167
43
116
82
15
82
167
161
118
197
43
58
118
58
184
171
1
24
141
167
75
166
118
14
171
87
24
14
1
75
239
43
43
78
43
199
116
184
51
177
96
87
239
24
95
199
72
70
14
23
118
153
119
119
85
177
43
82
98
174
24
55
32
195
94
118
177
94
199
174
199
1
57
116
68
7
94
43
149
90
152
70
24
48
177
94
177
149
174
160
177
174
119
118
167
197
14
167
177
143
149
149
177
174
147
239
43
153
153
185
177
24
24
118
14
149
149
149
32
14
21
69
113
94
153
118
119
197
55
130
177
119
197
100
168
118
188
174
24
177
130
239
52
14
32
199
14
14
96
118
147
177
197
82
23
24
127
174
153
215
177
174
118
177
215
1
215
14
119
149
43
118
52


131
183
9
215
177
8
82
118
43
75
1
118
1
80
1
24
188
178
24
174
75
42
53
141
199
162
193
174
1
38
118
32
26
177
51
193
32
21
183
70
24
75
38
1
177
118
118
4
239
118
118
177
23
193
123
118
118
42
118
75
167
48
118
1
1
24
1
118
16
24
118
84
16
57
40
123
118
32
199
191
118
75
177
131
188
24
182
75
183
188
43
14
141
21
188
72
177
1
24
90
131
118
118
125
14
177
118
118
199
32
118
149
185
24
6
24
24
118
239
1
199
32
118
24
215
174
14
43
118
153
14
1
141
118
118
70
153
153
118
24
174
123
71
215
1
215
24
215
118
24
153
72
118
35
118
215
174
102
14
70
24
215
118
14
239
14
21
43
14
21
177
4
215
14
215
215
118
143
118
90
14
1
118
215
24
1
177
72
133
177
149
145
196
94
43
24
14
14
70
56
24
140
100
239
143
56
75
149
24
161
215
239
43
14
145
188
215
183
118
177
14
72
24
215
145
109
24
118
24
24
157
1
118
118
24
24
102
239
24
193
118
118
174
177
32
176
102
118
174
174
14
118
141
75
199
55
118
22
239
14
239
145
140
14
171
215
215
174
173
159
24
32
48
177
1
116
75
195
149
9
14
25
58
1
1
118
167
43
116


177
177
160
1
185
146
177
118
185
239
1
177
185
1
183
61
83
75
75
75
118
1
167
177
91
185
167
190
185
177
178
75
118
24
190
118
177
75
83
177
75
118
118
177
190
55
116
177
178
177
118
118
177
177
192
177
145
75
68
193
118
178
118
177
178
19
187
118
70
177
118
180
190
190
190
75
177
191
141
1
180
118
94
192
185
177
145
32
177
118
75
185
239
75
51
91
145
94
35
75
190
177
183
1
83
239
177
118
94
193
116
177
75
118
185
83
94
177
183
75
239
114
190
55
143
75
177
177
177
91
118
178
177
76
239
177
185
118
118
1
190
185
1
118
190
118
19
239
118
193
193
118
43
145
190
177
190
177
19
75
183
83
10
1
177
24
90
1
177
94
167
177
1
177
64
118
1
178
118
1
178
91
59
177
177
215
177
75
19
215
193
55
167
178
191
184
118
56
167
70
70
118
70
177
90
178
145
94
61
185
200
177
215
118
149
177
187
177
177
185
190
215
175
143
118
55
75
1
131
61
19
190
193
239
176
35
118
91
177
3
190
1
190
177
177
171
177
180
177
146
118
118
185
177
191
145
178
94
167
43
183
193
177
167
190
1
177
190
190
193
185
188
177
177
94
1

118
239
84
177
199
124
199
118
24
239
123
84
177
177
239
118
239
118
239
239
61
76
118
118
85
239
177
95
118
75
51
116
71
177
166
146
239
239
24
177
215
118
116
118
177
239
239
171
118
239
118
165
166
177
118
64
177
177
239
177
118
24
177
239
174
177
118
239
104
239
156
177
118
177
177
118
14
131
177
56
239
239
154
177
177
51
24
239
85
239
122
118
174
61
51
239
177
167
51
141
118
118
177
24
177
154
118
177
118
118
118
77
239
239
171
215
118
177
177
118
118
22
122
118
76
159
118
122
118
61
118
239
118
48
239
118
116
239
90
51
24
118
215
118
239
177
199
195
118
177
118
118
239
95
118
177
71
70
24
117
177
239
118
24
177
177
177
61
14
142
177
84
239
199
24
24
118
82
118
64
239
75
239
118
239
76
239
100
118
118
239
215
239
177
239
51
177
118
138
82
239
118
85
138
239
118
118
239
118
118
1
63
118
177
195
118
14
177
64
156
118
118
118
239
166
24
75
146
239
118
138
76
56
32
118
56
118
118
118
50
239
118
239
215
1
177
24
118
51
239
118
24
43
215
167
177
14
177
177
24
118
166
122
177
118
118
167

In [62]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import sklearn.linear_model as models
import numpy as np
import pickle
import sys

import os

os.environ['CUDA_VISIBLE_DEVICES'] = "1"

!ls results

file_predictions = './results/' + 'DenseNet121c160_predictions_all.pickle'
fdata = open(file_predictions, 'rb')
predictions_dict = pickle.load(fdata)  # variables come out in the order you put them in
fdata.close()
predictions_all = predictions_dict['predictions_all']
images_all = predictions_dict['images_all']

print(predictions_all)

# Load image features
file_feature = './results/' + 'vgg19pre__features_all.pickle'
fdata = open(file_feature, 'rb')
features_dict = pickle.load(fdata)  # variables come out in the order you put them in
fdata.close()
features_all = features_dict['features_all']
labels_all = features_dict['labels_all']
images_all = features_dict['images_all']

print(features_all)
print(features_all.shape)
print(features_all[0].sum())
"""
no_zero_and_max = np.zeros(shape=(2, features_all.shape[0]))
for i in range(features_all.shape[0]):
    for j in range(features_all.shape[1]):
        if features_all[i, j] != 0:
            no_zero_and_max[0][i] += 1
    no_zero_and_max[1][i] = features_all[i].max()
print(no_zero_and_max)"""

print(predictions_all)

# Load image features
file_feature = './results/' + 'vgg19pre__features_all.pickle'
fdata = open(file_feature, 'rb')
features_dict = pickle.load(fdata)  # variables come out in the order you put them in
fdata.close()
features_all = features_dict['features_all']
labels_all = features_dict['labels_all']
images_all = features_dict['images_all']

print(features_all)
print(features_all.shape)
print(features_all[0].sum())
"""
no_zero_and_max = np.zeros(shape=(2, features_all.shape[0]))
for i in range(features_all.shape[0]):
    for j in range(features_all.shape[1]):
        if features_all[i, j] != 0:
            no_zero_and_max[0][i] += 1
    no_zero_and_max[1][i] = features_all[i].max()
print(no_zero_and_max)"""

# Calculate number
train_num = 0 
test_num = 0
#labels_all 
for lab in labels_all:
    if lab[0] != 't':
        train_num += 1
    else:
        test_num += 1
print(train_num, '\t', test_num)

import pandas as pd

f = open(r'/home/anhaoran/data/zero-shot-tianchi/dataset_B/DatasetB_20180919/attributes_per_class.txt')
lines_attr = f.readlines()
attributes = dict()
for each in lines_attr:
    tokens = each.split()
    #print(tokens)
    label = tokens[0]
    attr_list = list()
    for idx in range(1, 26):
        attr_list.append(float(tokens[idx]))
    if not (len(attr_list) == 25):
        print(('attributes number error\n'))
        exit()
    attributes[label] = attr_list
print(attributes)

list_train = list()
list_test = list()
for img_lab in attributes.keys():
    if len(img_lab[3:]) >= 3 and float(img_lab[3:]) >= 131:
        list_test.append(img_lab)
    else:
        list_train.append(img_lab)
print(len(list_train))
print(list_train)
print(len(list_test))
print(list_test)

print(len(list_train))
print(len(list_test))